// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-custom/graphql-gateway/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetBookIsbn struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookIsbn) Reset()         { *m = GetBookIsbn{} }
func (m *GetBookIsbn) String() string { return proto.CompactTextString(m) }
func (*GetBookIsbn) ProtoMessage()    {}
func (*GetBookIsbn) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *GetBookIsbn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookIsbn.Unmarshal(m, b)
}
func (m *GetBookIsbn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookIsbn.Marshal(b, m, deterministic)
}
func (m *GetBookIsbn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookIsbn.Merge(m, src)
}
func (m *GetBookIsbn) XXX_Size() int {
	return xxx_messageInfo_GetBookIsbn.Size(m)
}
func (m *GetBookIsbn) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookIsbn.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookIsbn proto.InternalMessageInfo

func (m *GetBookIsbn) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type GetBookStruct struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookStruct) Reset()         { *m = GetBookStruct{} }
func (m *GetBookStruct) String() string { return proto.CompactTextString(m) }
func (*GetBookStruct) ProtoMessage()    {}
func (*GetBookStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *GetBookStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookStruct.Unmarshal(m, b)
}
func (m *GetBookStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookStruct.Marshal(b, m, deterministic)
}
func (m *GetBookStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookStruct.Merge(m, src)
}
func (m *GetBookStruct) XXX_Size() int {
	return xxx_messageInfo_GetBookStruct.Size(m)
}
func (m *GetBookStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookStruct.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookStruct proto.InternalMessageInfo

func (m *GetBookStruct) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type CreateBookStruct struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookStruct) Reset()         { *m = CreateBookStruct{} }
func (m *CreateBookStruct) String() string { return proto.CompactTextString(m) }
func (*CreateBookStruct) ProtoMessage()    {}
func (*CreateBookStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *CreateBookStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookStruct.Unmarshal(m, b)
}
func (m *CreateBookStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookStruct.Marshal(b, m, deterministic)
}
func (m *CreateBookStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookStruct.Merge(m, src)
}
func (m *CreateBookStruct) XXX_Size() int {
	return xxx_messageInfo_CreateBookStruct.Size(m)
}
func (m *CreateBookStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookStruct.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookStruct proto.InternalMessageInfo

func (m *CreateBookStruct) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *CreateBookStruct) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "book.Book")
	proto.RegisterType((*GetBookIsbn)(nil), "book.GetBookIsbn")
	proto.RegisterType((*GetBookStruct)(nil), "book.GetBookStruct")
	proto.RegisterType((*CreateBookStruct)(nil), "book.CreateBookStruct")
}

func init() {
	proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8)
}

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x4c, 0xd2, 0x33, 0x4b, 0x32,
	0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xd3, 0x8b, 0x0a, 0x92, 0x75, 0x93, 0x4b, 0x8b, 0x4b,
	0xc0, 0xec, 0xc4, 0x82, 0x8c, 0xc2, 0x1c, 0xdd, 0xf4, 0xc4, 0x92, 0xd4, 0xf2, 0xc4, 0x4a, 0x18,
	0x1f, 0xa2, 0x57, 0xc9, 0x80, 0x8b, 0xc5, 0x29, 0x3f, 0x3f, 0x5b, 0x48, 0x88, 0x8b, 0x25, 0xb3,
	0x38, 0x29, 0x4f, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0x2d,
	0xc9, 0x2c, 0xc9, 0x49, 0x95, 0x60, 0x02, 0x0b, 0x42, 0x38, 0x4a, 0x8a, 0x5c, 0xdc, 0xee, 0xa9,
	0x25, 0x20, 0x4d, 0x9e, 0x20, 0x45, 0x58, 0x34, 0x2a, 0xe9, 0x73, 0xf1, 0x42, 0x95, 0x04, 0x97,
	0x14, 0x95, 0x26, 0x97, 0x08, 0xc9, 0x71, 0x81, 0xdd, 0x08, 0x56, 0xc4, 0x6d, 0xc4, 0xa5, 0x07,
	0x76, 0x3c, 0x48, 0x3e, 0x08, 0x2c, 0xae, 0x64, 0xc3, 0x25, 0xe0, 0x5c, 0x94, 0x9a, 0x58, 0x92,
	0x8a, 0xa4, 0x87, 0x68, 0x17, 0x19, 0xcd, 0x62, 0xe4, 0xe2, 0x06, 0x6b, 0x4c, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0x15, 0x72, 0xe0, 0x62, 0x87, 0x5a, 0x2f, 0x24, 0x08, 0xb1, 0x0a, 0xc9, 0xc1, 0x52,
	0xc2, 0x28, 0x42, 0x10, 0xcb, 0x94, 0x78, 0x17, 0x6d, 0xd5, 0xe6, 0xe4, 0x62, 0x4f, 0x87, 0x6a,
	0xf3, 0xe4, 0xe2, 0x42, 0xb8, 0x47, 0x48, 0x0c, 0xa2, 0x03, 0xdd, 0x85, 0x52, 0x98, 0x86, 0x2b,
	0x09, 0x2c, 0xda, 0xaa, 0xcd, 0x23, 0xc4, 0x95, 0x0c, 0x57, 0x9a, 0xc4, 0x06, 0x0e, 0x67, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xee, 0x8e, 0xc4, 0xb1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	GetBook(ctx context.Context, in *GetBookIsbn, opts ...grpc.CallOption) (*GetBookStruct, error)
	CreateBook(ctx context.Context, in *CreateBookStruct, opts ...grpc.CallOption) (*GetBookIsbn, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookIsbn, opts ...grpc.CallOption) (*GetBookStruct, error) {
	out := new(GetBookStruct)
	err := c.cc.Invoke(ctx, "/book.BookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookStruct, opts ...grpc.CallOption) (*GetBookIsbn, error) {
	out := new(GetBookIsbn)
	err := c.cc.Invoke(ctx, "/book.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	GetBook(context.Context, *GetBookIsbn) (*GetBookStruct, error)
	CreateBook(context.Context, *CreateBookStruct) (*GetBookIsbn, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) GetBook(ctx context.Context, req *GetBookIsbn) (*GetBookStruct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookServiceServer) CreateBook(ctx context.Context, req *CreateBookStruct) (*GetBookIsbn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookIsbn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookIsbn))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookStruct))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
