// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,5,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	UserId               int32    `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	Likes                int32    `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *Post) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Post) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

type GetPostRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type GetPostsRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsRequest) Reset()         { *m = GetPostsRequest{} }
func (m *GetPostsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostsRequest) ProtoMessage()    {}
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *GetPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsRequest.Unmarshal(m, b)
}
func (m *GetPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsRequest.Marshal(b, m, deterministic)
}
func (m *GetPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsRequest.Merge(m, src)
}
func (m *GetPostsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostsRequest.Size(m)
}
func (m *GetPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsRequest proto.InternalMessageInfo

func (m *GetPostsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetPostsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetPostsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPostsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsResponse) Reset()         { *m = GetPostsResponse{} }
func (m *GetPostsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse) ProtoMessage()    {}
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *GetPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse.Unmarshal(m, b)
}
func (m *GetPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse.Merge(m, src)
}
func (m *GetPostsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse.Size(m)
}
func (m *GetPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse proto.InternalMessageInfo

func (m *GetPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GetPostsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreatePostRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,3,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostRequest) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *CreatePostRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreatePostResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdatePostRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,4,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostRequest) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

type UpdatePostResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{8}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletePostRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{9}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeletePostRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeletePostResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

func (m *DeletePostResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateLikeRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLikeRequest) Reset()         { *m = CreateLikeRequest{} }
func (m *CreateLikeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLikeRequest) ProtoMessage()    {}
func (*CreateLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{11}
}

func (m *CreateLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLikeRequest.Unmarshal(m, b)
}
func (m *CreateLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLikeRequest.Marshal(b, m, deterministic)
}
func (m *CreateLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLikeRequest.Merge(m, src)
}
func (m *CreateLikeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLikeRequest.Size(m)
}
func (m *CreateLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLikeRequest proto.InternalMessageInfo

func (m *CreateLikeRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateLikeRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type CreateLikeResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLikeResponse) Reset()         { *m = CreateLikeResponse{} }
func (m *CreateLikeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLikeResponse) ProtoMessage()    {}
func (*CreateLikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{12}
}

func (m *CreateLikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLikeResponse.Unmarshal(m, b)
}
func (m *CreateLikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLikeResponse.Marshal(b, m, deterministic)
}
func (m *CreateLikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLikeResponse.Merge(m, src)
}
func (m *CreateLikeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLikeResponse.Size(m)
}
func (m *CreateLikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLikeResponse proto.InternalMessageInfo

func (m *CreateLikeResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateLikeResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteLikeRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLikeRequest) Reset()         { *m = DeleteLikeRequest{} }
func (m *DeleteLikeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLikeRequest) ProtoMessage()    {}
func (*DeleteLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{13}
}

func (m *DeleteLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLikeRequest.Unmarshal(m, b)
}
func (m *DeleteLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLikeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLikeRequest.Merge(m, src)
}
func (m *DeleteLikeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLikeRequest.Size(m)
}
func (m *DeleteLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLikeRequest proto.InternalMessageInfo

func (m *DeleteLikeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteLikeResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLikeResponse) Reset()         { *m = DeleteLikeResponse{} }
func (m *DeleteLikeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLikeResponse) ProtoMessage()    {}
func (*DeleteLikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{14}
}

func (m *DeleteLikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLikeResponse.Unmarshal(m, b)
}
func (m *DeleteLikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLikeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLikeResponse.Merge(m, src)
}
func (m *DeleteLikeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLikeResponse.Size(m)
}
func (m *DeleteLikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLikeResponse proto.InternalMessageInfo

func (m *DeleteLikeResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteLikeResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CheckLikedRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLikedRequest) Reset()         { *m = CheckLikedRequest{} }
func (m *CheckLikedRequest) String() string { return proto.CompactTextString(m) }
func (*CheckLikedRequest) ProtoMessage()    {}
func (*CheckLikedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{15}
}

func (m *CheckLikedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLikedRequest.Unmarshal(m, b)
}
func (m *CheckLikedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLikedRequest.Marshal(b, m, deterministic)
}
func (m *CheckLikedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLikedRequest.Merge(m, src)
}
func (m *CheckLikedRequest) XXX_Size() int {
	return xxx_messageInfo_CheckLikedRequest.Size(m)
}
func (m *CheckLikedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLikedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLikedRequest proto.InternalMessageInfo

func (m *CheckLikedRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckLikedRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type CheckLikedResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Liked                bool     `protobuf:"varint,2,opt,name=liked,proto3" json:"liked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLikedResponse) Reset()         { *m = CheckLikedResponse{} }
func (m *CheckLikedResponse) String() string { return proto.CompactTextString(m) }
func (*CheckLikedResponse) ProtoMessage()    {}
func (*CheckLikedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{16}
}

func (m *CheckLikedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLikedResponse.Unmarshal(m, b)
}
func (m *CheckLikedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLikedResponse.Marshal(b, m, deterministic)
}
func (m *CheckLikedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLikedResponse.Merge(m, src)
}
func (m *CheckLikedResponse) XXX_Size() int {
	return xxx_messageInfo_CheckLikedResponse.Size(m)
}
func (m *CheckLikedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLikedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLikedResponse proto.InternalMessageInfo

func (m *CheckLikedResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckLikedResponse) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func init() {
	proto.RegisterType((*Post)(nil), "post.Post")
	proto.RegisterType((*GetPostRequest)(nil), "post.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "post.GetPostResponse")
	proto.RegisterType((*GetPostsRequest)(nil), "post.GetPostsRequest")
	proto.RegisterType((*GetPostsResponse)(nil), "post.GetPostsResponse")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "post.CreatePostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "post.UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "post.UpdatePostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "post.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "post.DeletePostResponse")
	proto.RegisterType((*CreateLikeRequest)(nil), "post.CreateLikeRequest")
	proto.RegisterType((*CreateLikeResponse)(nil), "post.CreateLikeResponse")
	proto.RegisterType((*DeleteLikeRequest)(nil), "post.DeleteLikeRequest")
	proto.RegisterType((*DeleteLikeResponse)(nil), "post.DeleteLikeResponse")
	proto.RegisterType((*CheckLikedRequest)(nil), "post.CheckLikedRequest")
	proto.RegisterType((*CheckLikedResponse)(nil), "post.CheckLikedResponse")
}

func init() {
	proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1)
}

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x1d, 0x3b, 0x49, 0x27, 0x52, 0x68, 0x96, 0x10, 0x8c, 0x29, 0x55, 0xb4, 0xed, 0xa1,
	0xca, 0xa1, 0x56, 0xcb, 0x2d, 0x1c, 0x8b, 0x84, 0x40, 0x15, 0x42, 0x41, 0x11, 0x12, 0xb7, 0x10,
	0x6f, 0x5b, 0x2b, 0xa9, 0xd7, 0xd8, 0x9b, 0x72, 0x88, 0x72, 0xe1, 0x17, 0x20, 0xf1, 0xd3, 0x38,
	0x72, 0xe5, 0x87, 0xa0, 0xfd, 0xb2, 0xd7, 0x36, 0xe6, 0x00, 0xbd, 0x79, 0xd6, 0x3b, 0x6f, 0xde,
	0xcc, 0xbc, 0x67, 0x03, 0x24, 0x34, 0x63, 0xa7, 0x49, 0x4a, 0x19, 0x45, 0x0e, 0x7f, 0xf6, 0x0f,
	0xae, 0x29, 0xbd, 0x5e, 0x93, 0x60, 0x91, 0x44, 0xc1, 0x22, 0x8e, 0x29, 0x5b, 0xb0, 0x88, 0xc6,
	0x99, 0xbc, 0x83, 0xbf, 0x59, 0xe0, 0xbc, 0xa3, 0x19, 0x43, 0x7d, 0xb0, 0xa3, 0xd0, 0xb3, 0xc6,
	0xd6, 0x89, 0x3b, 0xb3, 0xa3, 0x10, 0x0d, 0xc1, 0x65, 0x11, 0x5b, 0x13, 0xcf, 0x1e, 0x5b, 0x27,
	0x7b, 0x33, 0x19, 0x20, 0x0f, 0x3a, 0x4b, 0x1a, 0x33, 0x12, 0x33, 0xaf, 0x25, 0xce, 0x75, 0x88,
	0x7c, 0xe8, 0x26, 0x37, 0x94, 0xd1, 0x79, 0xba, 0xf6, 0x5c, 0xf1, 0x2a, 0x8f, 0xd1, 0x08, 0xda,
	0x9b, 0x8c, 0xa4, 0xaf, 0x43, 0xaf, 0x2d, 0xf0, 0x55, 0xc4, 0x6b, 0xac, 0xa3, 0x15, 0xc9, 0xbc,
	0x8e, 0x38, 0x96, 0x01, 0x1e, 0x43, 0xff, 0x15, 0x61, 0x9c, 0xd4, 0x8c, 0x7c, 0xde, 0x90, 0x3a,
	0x37, 0x7c, 0x06, 0x0f, 0xf2, 0x1b, 0x59, 0x42, 0xe3, 0x8c, 0xa0, 0x43, 0x10, 0xdd, 0x8a, 0x4b,
	0xbd, 0x73, 0x38, 0x15, 0x63, 0x10, 0x37, 0xc4, 0x39, 0x5e, 0xe6, 0x29, 0x99, 0x46, 0x15, 0xd5,
	0x6f, 0x23, 0xa6, 0x80, 0x65, 0xc0, 0xb9, 0xd2, 0xab, 0xab, 0x8c, 0x30, 0xd1, 0xb8, 0x3b, 0x53,
	0x91, 0xe2, 0xd0, 0xca, 0xe7, 0x83, 0xc0, 0x89, 0x17, 0xb7, 0xc4, 0x73, 0x44, 0xaf, 0xe2, 0x19,
	0xbf, 0x81, 0xfd, 0xa2, 0x88, 0x22, 0x36, 0x06, 0x97, 0x13, 0xc8, 0x3c, 0x6b, 0xdc, 0xaa, 0x30,
	0x93, 0x2f, 0x38, 0x8f, 0x25, 0xdd, 0xc4, 0xba, 0xa0, 0x0c, 0xf0, 0x17, 0x18, 0x5c, 0xa4, 0x64,
	0xc1, 0x88, 0x39, 0x88, 0x7c, 0x29, 0x56, 0xc3, 0x52, 0xec, 0xe6, 0xa5, 0xb4, 0x1a, 0x97, 0xe2,
	0x98, 0x4b, 0xc1, 0xc7, 0x80, 0xcc, 0xc2, 0xaa, 0x8d, 0xea, 0x0a, 0x28, 0x0c, 0xe6, 0x49, 0x58,
	0xa1, 0x77, 0x9f, 0x1a, 0x72, 0xca, 0x74, 0x39, 0x2d, 0xb3, 0x60, 0x03, 0xad, 0x17, 0x30, 0x78,
	0x49, 0xd6, 0xe4, 0xef, 0xb4, 0x8a, 0xce, 0xed, 0x6a, 0xe7, 0x66, 0x72, 0x43, 0x89, 0x0b, 0xbd,
	0x98, 0xcb, 0x68, 0x45, 0x74, 0x89, 0x02, 0xd2, 0x2a, 0x29, 0x7c, 0x04, 0x6d, 0xbe, 0xe4, 0xa2,
	0x94, 0x8c, 0xf0, 0x54, 0x0f, 0x59, 0x82, 0xfc, 0xb9, 0x54, 0x83, 0x32, 0x8e, 0x74, 0x8f, 0x26,
	0x81, 0x2a, 0xcb, 0xa9, 0xee, 0xe5, 0x1f, 0x0a, 0xf0, 0x0e, 0x6f, 0xc8, 0x72, 0xc5, 0x53, 0xc3,
	0xff, 0xe9, 0xd0, 0x00, 0x69, 0x26, 0xc0, 0x4d, 0x2f, 0x93, 0xbb, 0xf2, 0x0b, 0x10, 0x9e, 0xff,
	0x74, 0xa1, 0xc7, 0x77, 0xf0, 0x9e, 0xa4, 0x77, 0xd1, 0x92, 0xa0, 0xb7, 0xd0, 0x51, 0xbe, 0x42,
	0x43, 0xe9, 0x9f, 0xf2, 0x07, 0xc2, 0x7f, 0x54, 0x39, 0x95, 0xd5, 0xf0, 0xe8, 0xeb, 0x8f, 0x5f,
	0xdf, 0xed, 0x7d, 0xd4, 0x0f, 0xee, 0xce, 0x02, 0x61, 0xb6, 0x60, 0x1b, 0x85, 0x3b, 0x74, 0x09,
	0x5d, 0xed, 0x53, 0x54, 0x4e, 0xd5, 0x1f, 0x07, 0x7f, 0x54, 0x3d, 0x56, 0x90, 0x03, 0x01, 0xd9,
	0x43, 0x7b, 0x39, 0x24, 0x9a, 0x03, 0x14, 0x86, 0x41, 0x8f, 0x65, 0x62, 0xcd, 0xbb, 0xbe, 0x57,
	0x7f, 0xa1, 0x30, 0x87, 0x02, 0xb3, 0x8f, 0x0b, 0xcc, 0xa9, 0x35, 0x41, 0x1f, 0x01, 0x0a, 0xc1,
	0x6b, 0xd8, 0x9a, 0xe7, 0x34, 0x6c, 0xdd, 0x1b, 0xf8, 0x89, 0x80, 0x7d, 0xe8, 0x57, 0xba, 0xe7,
	0xd8, 0x04, 0xa0, 0x50, 0xba, 0xc6, 0xae, 0x19, 0x47, 0x63, 0xd7, 0x4d, 0x81, 0x8f, 0x05, 0xf6,
	0xe1, 0xe4, 0xa0, 0x8c, 0x1d, 0x70, 0x51, 0x04, 0x5b, 0x29, 0x8d, 0x5d, 0x31, 0x19, 0x2e, 0x82,
	0xf2, 0x64, 0x0c, 0xed, 0x96, 0x27, 0x63, 0xea, 0xb5, 0x3c, 0x19, 0xf1, 0x77, 0xe0, 0xec, 0x3f,
	0x68, 0xf6, 0x26, 0x6c, 0xcd, 0x12, 0x65, 0xf6, 0x25, 0x58, 0xa5, 0x8b, 0x49, 0x3f, 0x87, 0x95,
	0xba, 0x08, 0x01, 0x0a, 0xcd, 0xe6, 0x7c, 0xab, 0x56, 0xc8, 0xf9, 0xd6, 0xe4, 0x8d, 0x8f, 0x04,
	0xf0, 0x33, 0xf4, 0xd4, 0x00, 0x56, 0xc3, 0x08, 0xb6, 0xd2, 0x18, 0xbb, 0x4f, 0x6d, 0xf1, 0xe7,
	0x7d, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x87, 0x43, 0x29, 0xc8, 0xab, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	CreateLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*CreateLikeResponse, error)
	DeleteLike(ctx context.Context, in *DeleteLikeRequest, opts ...grpc.CallOption) (*DeleteLikeResponse, error)
	CheckLiked(ctx context.Context, in *CheckLikedRequest, opts ...grpc.CallOption) (*CheckLikedResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPosts(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*CreateLikeResponse, error) {
	out := new(CreateLikeResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/CreateLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteLike(ctx context.Context, in *DeleteLikeRequest, opts ...grpc.CallOption) (*DeleteLikeResponse, error) {
	out := new(DeleteLikeResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/DeleteLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CheckLiked(ctx context.Context, in *CheckLikedRequest, opts ...grpc.CallOption) (*CheckLikedResponse, error) {
	out := new(CheckLikedResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/CheckLiked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	GetPosts(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	CreateLike(context.Context, *CreateLikeRequest) (*CreateLikeResponse, error)
	DeleteLike(context.Context, *DeleteLikeRequest) (*DeleteLikeResponse, error)
	CheckLiked(context.Context, *CheckLikedRequest) (*CheckLikedResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostServiceServer) GetPosts(ctx context.Context, req *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedPostServiceServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedPostServiceServer) CreateLike(ctx context.Context, req *CreateLikeRequest) (*CreateLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLike not implemented")
}
func (*UnimplementedPostServiceServer) DeleteLike(ctx context.Context, req *DeleteLikeRequest) (*DeleteLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLike not implemented")
}
func (*UnimplementedPostServiceServer) CheckLiked(ctx context.Context, req *CheckLikedRequest) (*CheckLikedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLiked not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPosts(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreateLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreateLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/CreateLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreateLike(ctx, req.(*CreateLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/DeleteLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteLike(ctx, req.(*DeleteLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CheckLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CheckLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/CheckLiked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CheckLiked(ctx, req.(*CheckLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPost",
			Handler:    _PostService_GetPost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _PostService_GetPosts_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
		{
			MethodName: "CreateLike",
			Handler:    _PostService_CreateLike_Handler,
		},
		{
			MethodName: "DeleteLike",
			Handler:    _PostService_DeleteLike_Handler,
		},
		{
			MethodName: "CheckLiked",
			Handler:    _PostService_CheckLiked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
